import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  en: {
    // Navbar
    "nav.courses": "Courses",
    "nav.blog": "Blog",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.login": "Log In",
    "nav.getStarted": "Get Started Free",
    
    // Hero
    "hero.badge": "🎓 Trusted by 2M+ learners worldwide",
    "hero.title1": "Master New Skills",
    "hero.title2": "Transform Your Future",
    "hero.subtitle": "Join thousands of learners advancing their careers with expert-led courses in technology, business, and creative skills.",
    "hero.cta1": "Start Learning Free",
    "hero.cta2": "Watch Demo",
    "hero.stats.students": "Active Students",
    "hero.stats.courses": "Courses",
    "hero.stats.rating": "Rating",
    
    // Stats Section
    "stats.students": "Active Students",
    "stats.courses": "Expert Courses",
    "stats.countries": "Countries",
    "stats.success": "Success Rate",
    
    // Features
    "features.badge": "Why Choose Us",
    "features.title1": "Everything You Need to",
    "features.title2": " Succeed",
    "features.subtitle": "Our platform is designed with your success in mind, offering comprehensive tools and resources for effective learning.",
    "features.expertCourses": "Expert-Led Courses",
    "features.expertCoursesDesc": "Learn from industry professionals and thought leaders who bring real-world experience to every lesson.",
    "features.interactive": "Interactive Learning",
    "features.interactiveDesc": "Engage with hands-on projects, quizzes, and coding exercises that reinforce your knowledge.",
    "features.pace": "Learn at Your Pace",
    "features.paceDesc": "Access courses anytime, anywhere. Our flexible platform adapts to your schedule and learning style.",
    "features.certificates": "Earn Certificates",
    "features.certificatesDesc": "Showcase your achievements with industry-recognized certificates upon course completion.",
    "features.community": "Community Support",
    "features.communityDesc": "Join a global community of learners. Collaborate, discuss, and grow together.",
    "features.lifetime": "Lifetime Access",
    "features.lifetimeDesc": "Purchase once, learn forever. Get lifetime access to all course materials and future updates.",
    
    // Courses
    "courses.badge": "Popular Courses",
    "courses.title1": "Explore Our",
    "courses.title2": " Top Courses",
    "courses.subtitle": "Discover hand-picked courses designed to help you achieve your learning goals and advance your career.",
    "courses.viewAll": "View All Courses",
    "courses.enroll": "Enroll Now",
    "courses.students": "students",
    
    // CTA
    "cta.title1": "Ready to Start Your",
    "cta.title2": "Learning Journey?",
    "cta.subtitle": "Join over 2 million learners worldwide and take the first step towards achieving your goals. Start learning for free today.",
    "cta.button1": "Get Started For Free",
    "cta.button2": "Browse Courses",
    "cta.note": "No credit card required • Free forever plan available",
    
    // Footer
    "footer.description": "Empowering learners worldwide with high-quality education and expert-led courses.",
    "footer.platform": "Platform",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.allCourses": "All Courses",
    "footer.enterprise": "Enterprise",
    "footer.becomeInstructor": "Become Instructor",
    "footer.mobileApp": "Mobile App",
    "footer.aboutUs": "About Us",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.helpCenter": "Help Center",
    "footer.contactUs": "Contact Us",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.cookies": "Cookies",
    "footer.rights": "All rights reserved.",
    
    // About Page
    "about.heroTitle1": "Transforming Lives Through",
    "about.heroTitle2": "Education",
    "about.heroSubtitle": "We're on a mission to make world-class education accessible to everyone, everywhere. Join us in shaping the future of learning.",
    "about.ourMission": "Our Mission",
    "about.missionText": "To empower individuals worldwide with the skills and knowledge they need to thrive in the digital age. We believe that quality education should not be a privilege but a right accessible to all.",
    "about.ourVision": "Our Vision",
    "about.visionText": "To become the world's most trusted and innovative learning platform, where anyone can acquire new skills, advance their careers, and unlock their full potential through transformative education.",
    "about.coreValues": "Our Core Values",
    "about.valuesSubtitle": "These principles guide everything we do and shape our culture",
    "about.excellence": "Excellence",
    "about.excellenceDesc": "We strive for the highest quality in everything we create, from course content to user experience.",
    "about.passion": "Passion",
    "about.passionDesc": "We're driven by a genuine love for education and helping others achieve their potential.",
    "about.community": "Community",
    "about.communityDesc": "We believe learning is better together and foster a supportive global community.",
    "about.accessibility": "Accessibility",
    "about.accessibilityDesc": "Education should be available to everyone, regardless of location or background.",
    "about.meetTeam": "Meet Our Team",
    "about.teamSubtitle": "Passionate educators and technologists working together to revolutionize learning",
    "about.ourJourney": "Our Journey",
    "about.journeySubtitle": "From a small idea to a global platform",
    "about.studentsWorldwide": "Students Worldwide",
    "about.expertInstructors": "Expert Instructors",
    "about.coursesAvailable": "Courses Available",
    "about.countriesReached": "Countries Reached",
    "about.joinTeam": "Join Our Growing Team",
    "about.joinTeamDesc": "We're always looking for passionate individuals to help us transform education. Check out our open positions and be part of something meaningful.",
    "about.viewPositions": "View Open Positions",
    
    // Contact Page
    "contact.badge": "Contact Us",
    "contact.heroTitle1": "We'd Love to",
    "contact.heroTitle2": "Hear From You",
    "contact.heroSubtitle": "Have questions about our courses or need help with your learning journey? Our team is here to assist you every step of the way.",
    "contact.sendMessage": "Send us a Message",
    "contact.fullName": "Full Name",
    "contact.emailAddress": "Email Address",
    "contact.subject": "Subject",
    "contact.subjectPlaceholder": "How can we help you?",
    "contact.message": "Message",
    "contact.messagePlaceholder": "Tell us more about your inquiry...",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.quickContact": "Quick Contact",
    "contact.emailUs": "Email Us",
    "contact.weRespond": "We respond within 24 hours",
    "contact.callUs": "Call Us",
    "contact.callHours": "Mon-Fri, 9AM - 6PM EST",
    "contact.supportOptions": "Support Options",
    "contact.liveChat": "Live Chat",
    "contact.liveChatDesc": "Get instant help from our support team",
    "contact.startChat": "Start Chat",
    "contact.available247": "Available 24/7",
    "contact.helpCenter": "Help Center",
    "contact.helpCenterDesc": "Browse our comprehensive knowledge base",
    "contact.visitHelpCenter": "Visit Help Center",
    "contact.selfService": "Self-service",
    "contact.documentation": "Documentation",
    "contact.documentationDesc": "Detailed guides and API references",
    "contact.viewDocs": "View Docs",
    "contact.alwaysAvailable": "Always available",
    "contact.ourOffices": "Our Offices",
    "contact.officesSubtitle": "Visit us at one of our global locations or reach out to the nearest office.",
    "contact.messageSent": "Message sent!",
    "contact.messageSuccess": "We'll get back to you within 24 hours.",
    
    // Courses Page
    "coursesPage.title": "Explore Our",
    "coursesPage.titleHighlight": "Courses",
    "coursesPage.subtitle": "Discover hundreds of courses taught by expert instructors",
    "coursesPage.searchPlaceholder": "Search courses or instructors...",
    "coursesPage.all": "All",
    "coursesPage.development": "Development",
    "coursesPage.dataScience": "Data Science",
    "coursesPage.design": "Design",
    "coursesPage.marketing": "Marketing",
    "coursesPage.itSecurity": "IT & Security",
    "coursesPage.allLevels": "All Levels",
    "coursesPage.beginner": "Beginner",
    "coursesPage.intermediate": "Intermediate",
    "coursesPage.advanced": "Advanced",
    "coursesPage.allPrices": "All Prices",
    "coursesPage.under50": "Under $50",
    "coursesPage.showing": "Showing",
    "coursesPage.coursesCount": "courses",
    "coursesPage.noCoursesFound": "No courses found",
    "coursesPage.clearFilters": "Clear Filters",
    "coursesPage.by": "by",
    "coursesPage.enroll": "Enroll",
    "coursesPage.bestseller": "Bestseller",
    "coursesPage.hot": "Hot",
    "coursesPage.new": "New",
    "coursesPage.popular": "Popular",
    "coursesPage.hours": "hours",
    
    // Pricing Section
    "pricing.badge": "Pricing Plans",
    "pricing.title1": "Simple, Transparent",
    "pricing.title2": " Pricing",
    "pricing.subtitle": "Choose the plan that fits your learning goals. Upgrade or downgrade anytime.",
    "pricing.free": "Free",
    "pricing.freeDesc": "Perfect for getting started",
    "pricing.pro": "Pro",
    "pricing.proDesc": "Best for serious learners",
    "pricing.team": "Team",
    "pricing.teamDesc": "For teams and organizations",
    "pricing.month": "/month",
    "pricing.mostPopular": "Most Popular",
    "pricing.startFree": "Start Free",
    "pricing.startProTrial": "Start Pro Trial",
    "pricing.contactSales": "Contact Sales",
    "pricing.feature.free1": "Access to 10 free courses",
    "pricing.feature.free2": "Basic learning paths",
    "pricing.feature.free3": "Community forum access",
    "pricing.feature.free4": "Mobile app access",
    "pricing.feature.pro1": "Access to 200+ courses",
    "pricing.feature.pro2": "Personalized learning paths",
    "pricing.feature.pro3": "Certificate of completion",
    "pricing.feature.pro4": "Priority support",
    "pricing.feature.pro5": "Offline downloads",
    "pricing.feature.pro6": "Project reviews",
    "pricing.feature.team1": "Everything in Pro",
    "pricing.feature.team2": "Team management dashboard",
    "pricing.feature.team3": "Progress tracking & analytics",
    "pricing.feature.team4": "Custom learning paths",
    "pricing.feature.team5": "Dedicated account manager",
    "pricing.feature.team6": "API access",
    
    // Testimonials Section
    "testimonials.badge": "Success Stories",
    "testimonials.title1": "What Our Students",
    "testimonials.title2": " Say",
    "testimonials.subtitle": "Join thousands of satisfied learners who have transformed their careers with our platform.",
    "testimonials.name1": "Alex Thompson",
    "testimonials.role1": "Software Developer",
    "testimonials.company1": "Google",
    "testimonials.content1": "EduLearn completely transformed my career. The courses are comprehensive, well-structured, and the instructors are genuinely passionate about teaching.",
    "testimonials.name2": "Maria Garcia",
    "testimonials.role2": "UX Designer",
    "testimonials.company2": "Spotify",
    "testimonials.content2": "I went from knowing nothing about design to landing my dream job. The hands-on projects and mentor feedback were invaluable.",
    "testimonials.name3": "James Wilson",
    "testimonials.role3": "Data Analyst",
    "testimonials.company3": "Amazon",
    "testimonials.content3": "The data science curriculum here is top-notch. Real-world projects and industry-relevant skills helped me stand out in interviews.",
    "testimonials.at": "at",
    
    // Blog Page
    "blog.badge": "Our Blog",
    "blog.title1": "Insights & ",
    "blog.title2": "Resources",
    "blog.subtitle": "Stay updated with the latest trends in education, technology, and career development through our expert-written articles.",
    "blog.searchPlaceholder": "Search articles...",
    "blog.all": "All",
    "blog.career": "Career",
    "blog.development": "Development",
    "blog.aiMl": "AI & ML",
    "blog.education": "Education",
    "blog.cloud": "Cloud",
    "blog.featured": "Featured Articles",
    "blog.allArticles": "All Articles",
    "blog.articles": "Articles",
    "blog.noArticles": "No articles found matching your criteria.",
    "blog.newsletter": "Subscribe to Our Newsletter",
    "blog.newsletterDesc": "Get the latest articles, tutorials, and learning tips delivered straight to your inbox.",
    "blog.emailPlaceholder": "Enter your email",
    "blog.subscribe": "Subscribe",
    "blog.minRead": "min read",
    
    // Course Detail Page
    "courseDetail.backToCourses": "Back to Courses",
    "courseDetail.bestseller": "Bestseller",
    "courseDetail.updated": "Updated",
    "courseDetail.ratings": "ratings",
    "courseDetail.students": "students",
    "courseDetail.createdBy": "Created by",
    "courseDetail.lectures": "lectures",
    "courseDetail.certificateIncluded": "Certificate included",
    "courseDetail.previewCourse": "Preview this course",
    "courseDetail.off": "off",
    "courseDetail.enrollNow": "Enroll Now",
    "courseDetail.addToWishlist": "Add to Wishlist",
    "courseDetail.moneyBack": "30-Day Money-Back Guarantee",
    "courseDetail.courseIncludes": "This course includes:",
    "courseDetail.share": "Share",
    "courseDetail.whatYouLearn": "What you'll learn",
    "courseDetail.requirements": "Requirements",
    "courseDetail.courseCurriculum": "Course Curriculum",
    "courseDetail.sections": "sections",
    "courseDetail.preview": "Preview",
    "courseDetail.yourInstructor": "Your Instructor",
    "courseDetail.instructorRating": "Instructor Rating",
    "courseDetail.courses": "Courses",
    "courseDetail.studentReviews": "Student Reviews",
    "courseDetail.courseRating": "Course Rating",
    "courseDetail.showAllReviews": "Show All Reviews",
    "courseDetail.hoursOnDemand": "hours of on-demand video",
    "courseDetail.lecturesCovering": "lectures covering all topics",
    "courseDetail.realWorldProjects": "real-world projects",
    "courseDetail.downloadableResources": "Downloadable resources",
    "courseDetail.certificateCompletion": "Certificate of completion",
    "courseDetail.lifetimeAccess": "Lifetime access",
    "courseDetail.mobileAccess": "Mobile and TV access",
    "courseDetail.moneyBackGuarantee": "30-day money-back guarantee",
    "courseDetail.noProgramming": "No programming experience needed",
    "courseDetail.computerInternet": "A computer with internet access",
    "courseDetail.desireToLearn": "Desire to learn and build projects",
    "courseDetail.buildProjects": "Build 15+ real-world web projects",
    "courseDetail.masterHTML": "Master HTML5, CSS3, and modern JavaScript",
    "courseDetail.createResponsive": "Create responsive websites from scratch",
    "courseDetail.learnReact": "Learn React and build single-page applications",
    "courseDetail.understandBackend": "Understand backend development with Node.js",
    "courseDetail.workWithDB": "Work with databases like MongoDB",
    "courseDetail.deployCloud": "Deploy applications to the cloud",
    "courseDetail.writeClean": "Write clean, maintainable code",
    
    // Dashboard Page
    "dashboard.student": "Student",
    "dashboard.admin": "Admin",
    "dashboard.myCourses": "My Courses",
    "dashboard.progress": "Progress",
    "dashboard.certificates": "Certificates",
    "dashboard.schedule": "Schedule",
    "dashboard.profile": "Profile",
    "dashboard.logout": "Logout",
    "dashboard.welcomeBack": "Welcome back, John! 👋",
    "dashboard.continueJourney": "Continue your learning journey. You're making great progress!",
    "dashboard.enrolledCourses": "Enrolled Courses",
    "dashboard.hoursLearned": "Hours Learned",
    "dashboard.avgProgress": "Avg. Progress",
    "dashboard.continueLearning": "Continue Learning",
    "dashboard.viewAll": "View All",
    "dashboard.next": "Next:",
    "dashboard.continue": "Continue",
    "dashboard.by": "by",
    "dashboard.recentAchievements": "Recent Achievements",
    "dashboard.upcomingDeadlines": "Upcoming Deadlines",
    "dashboard.adminDashboard": "Admin Dashboard 🎛️",
    "dashboard.manageDescription": "Manage courses, students, and platform analytics.",
    "dashboard.totalStudents": "Total Students",
    "dashboard.totalCourses": "Total Courses",
    "dashboard.revenue": "Revenue",
    "dashboard.certificatesIssued": "Certificates Issued",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.addNewCourse": "Add New Course",
    "dashboard.manageUsers": "Manage Users",
    "dashboard.viewAnalytics": "View Analytics",
    "dashboard.settings": "Settings",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.firstCourse": "First Course",
    "dashboard.firstCourseDesc": "Enrolled in your first course",
    "dashboard.bookworm": "Bookworm",
    "dashboard.bookwormDesc": "Completed 5 lessons in one day",
    "dashboard.risingStar": "Rising Star",
    "dashboard.risingStarDesc": "Earned your first certificate",
    
    // Teacher Dashboard
    "dashboard.teacher": "Teacher",
    "dashboard.teacherDashboard": "Teacher Dashboard 📚",
    "dashboard.teacherDescription": "Manage your courses, students, and track performance.",
    "dashboard.myCoursesTaught": "My Courses",
    "dashboard.totalStudentsEnrolled": "Total Students",
    "dashboard.courseRevenue": "Course Revenue",
    "dashboard.avgRating": "Avg. Rating",
    "dashboard.manageCourses": "Manage Courses",
    "dashboard.createCourse": "Create Course",
    "dashboard.editCourse": "Edit Course",
    "dashboard.viewEnrollments": "View Enrollments",
    "dashboard.coursePerformance": "Course Performance",
    "dashboard.studentProgress": "Student Progress",
    "dashboard.recentEnrollments": "Recent Enrollments",
    "dashboard.courseFeedback": "Course Feedback",
    "dashboard.uploadContent": "Upload Content",
    "dashboard.viewReviews": "View Reviews",
    "dashboard.respondToQuestions": "Respond to Questions",
    "dashboard.pendingQuestions": "Pending Questions",
    "dashboard.courseStats": "Course Stats",
    "dashboard.earnings": "Earnings",
    "dashboard.withdrawFunds": "Withdraw Funds",
    "dashboard.paymentHistory": "Payment History",
    
    // Blog Post Page
    "blogPost.backToBlog": "Back to Blog",
    "blogPost.articleNotFound": "Article not found",
    "blogPost.like": "Like",
    "blogPost.save": "Save",
    "blogPost.share": "Share",
    "blogPost.shareArticle": "Share this article",
    "blogPost.relatedArticles": "Related Articles",
    "blogPost.minRead": "min read",
    
    // Help Center Page
    "helpCenter.title": "How can we help you?",
    "helpCenter.subtitle": "Search our knowledge base or browse categories below",
    "helpCenter.searchPlaceholder": "Search for help articles...",
    "helpCenter.popularArticles": "Popular Articles",
    "helpCenter.browseByCategory": "Browse by Category",
    "helpCenter.stillNeedHelp": "Still need help?",
    "helpCenter.supportTeam": "Our support team is here to assist you",
    "helpCenter.emailUs": "Email Us",
    "helpCenter.emailResponse": "Get a response within 24 hours",
    "helpCenter.sendEmail": "Send Email",
    "helpCenter.liveChat": "Live Chat",
    "helpCenter.chatRealTime": "Chat with us in real-time",
    "helpCenter.startChat": "Start Chat",
    "helpCenter.callUs": "Call Us",
    "helpCenter.callHours": "Mon-Fri, 9am-6pm PST",
    "helpCenter.gettingStarted": "Getting Started",
    "helpCenter.gettingStartedDesc": "Learn the basics of using EduLearn",
    "helpCenter.coursesLearning": "Courses & Learning",
    "helpCenter.coursesLearningDesc": "Everything about taking courses",
    "helpCenter.paymentsBilling": "Payments & Billing",
    "helpCenter.paymentsBillingDesc": "Manage your payments and subscriptions",
    "helpCenter.accountManagement": "Account Management",
    "helpCenter.accountManagementDesc": "Update your account settings",
    "helpCenter.technicalIssues": "Technical Issues",
    "helpCenter.technicalIssuesDesc": "Troubleshoot common problems",
    "helpCenter.communitySupport": "Community & Support",
    "helpCenter.communitySupportDesc": "Connect with others",
    "helpCenter.article1": "How to create an account",
    "helpCenter.article2": "Navigating the platform",
    "helpCenter.article3": "Finding your first course",
    "helpCenter.article4": "Setting up your profile",
    "helpCenter.article5": "Enrolling in courses",
    "helpCenter.article6": "Tracking your progress",
    "helpCenter.article7": "Downloading resources",
    "helpCenter.article8": "Earning certificates",
    "helpCenter.article9": "Payment methods",
    "helpCenter.article10": "Subscription plans",
    "helpCenter.article11": "Refund policy",
    "helpCenter.article12": "Invoice and receipts",
    "helpCenter.article13": "Changing password",
    "helpCenter.article14": "Updating email",
    "helpCenter.article15": "Privacy settings",
    "helpCenter.article16": "Deleting account",
    "helpCenter.article17": "Video playback issues",
    "helpCenter.article18": "Login problems",
    "helpCenter.article19": "Browser compatibility",
    "helpCenter.article20": "Mobile app help",
    "helpCenter.article21": "Discussion forums",
    "helpCenter.article22": "Study groups",
    "helpCenter.article23": "Contacting instructors",
    "helpCenter.article24": "Reporting issues",
    "helpCenter.popular1": "How do I get a refund?",
    "helpCenter.popular2": "Can I download course videos?",
    "helpCenter.popular3": "How do certificates work?",
    "helpCenter.popular4": "Why won't my video play?",
    "helpCenter.popular5": "How to cancel my subscription",
    
    // Privacy Policy Page
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Your privacy is important to us. This policy explains how we collect, use, and protect your personal information.",
    "privacy.lastUpdated": "Last updated: December 2024",
    "privacy.questions": "Questions About Privacy?",
    "privacy.contactText": "If you have any questions about this Privacy Policy or our data practices, please contact our Data Protection Officer at:",
    "privacy.section1Title": "Information We Collect",
    "privacy.section1Content": "We collect information you provide directly to us, such as when you create an account, enroll in a course, make a purchase, or contact us for support. This includes:\n\n• Personal information (name, email address, phone number)\n• Payment information (processed securely through our payment providers)\n• Course progress and completion data\n• Communications with instructors and other students\n• Feedback and survey responses",
    "privacy.section2Title": "How We Use Your Information",
    "privacy.section2Content": "We use the information we collect to:\n\n• Provide, maintain, and improve our services\n• Process transactions and send related information\n• Send you technical notices, updates, and support messages\n• Respond to your comments, questions, and requests\n• Personalize your learning experience\n• Monitor and analyze trends, usage, and activities",
    "privacy.section3Title": "Information Sharing",
    "privacy.section3Content": "We do not sell, trade, or otherwise transfer your personal information to outside parties except:\n\n• With your consent\n• To instructors for courses you're enrolled in\n• To service providers who assist in our operations\n• To comply with legal obligations\n• To protect our rights and prevent fraud",
    "privacy.section4Title": "Data Security",
    "privacy.section4Content": "We implement appropriate technical and organizational measures to protect your personal information:\n\n• Encryption of data in transit and at rest\n• Regular security assessments and audits\n• Access controls and authentication\n• Secure data centers with 24/7 monitoring\n• Employee training on data protection",
    "privacy.section5Title": "Your Rights",
    "privacy.section5Content": "You have the right to:\n\n• Access your personal information\n• Correct inaccurate data\n• Request deletion of your data\n• Object to processing of your data\n• Export your data in a portable format\n• Withdraw consent at any time",
    "privacy.section6Title": "Cookies & Tracking",
    "privacy.section6Content": "We use cookies and similar tracking technologies to:\n\n• Remember your preferences and settings\n• Understand how you use our platform\n• Deliver relevant content and advertisements\n• Analyze and improve our services\n\nYou can control cookies through your browser settings.",
    
    // Create Course Page
    "createCourse.backToDashboard": "Back to Dashboard",
    "createCourse.title": "Create New Course",
    "createCourse.subtitle": "Fill in the details below to create your course. You can edit these later.",
    "createCourse.basicInfo": "Basic Information",
    "createCourse.courseTitle": "Course Title",
    "createCourse.courseTitlePlaceholder": "e.g., Complete Web Development Bootcamp",
    "createCourse.shortDescription": "Short Description",
    "createCourse.shortDescriptionPlaceholder": "Brief overview of your course (max 150 characters)",
    "createCourse.fullDescription": "Full Description",
    "createCourse.fullDescriptionPlaceholder": "Detailed description of what students will learn...",
    "createCourse.category": "Category",
    "createCourse.selectCategory": "Select a category",
    "createCourse.level": "Level",
    "createCourse.selectLevel": "Select a level",
    "createCourse.pricing": "Pricing",
    "createCourse.price": "Price (USD)",
    "createCourse.discountPrice": "Discount Price (Optional)",
    "createCourse.durationMedia": "Duration & Media",
    "createCourse.estimatedDuration": "Estimated Duration",
    "createCourse.durationPlaceholder": "e.g., 20 hours",
    "createCourse.thumbnail": "Course Thumbnail",
    "createCourse.uploadThumbnail": "Click to upload an image (JPG, PNG)",
    "createCourse.curriculum": "Curriculum",
    "createCourse.addSection": "Add Section",
    "createCourse.section": "Section",
    "createCourse.sectionTitlePlaceholder": "Section title (e.g., Getting Started)",
    "createCourse.lessonTitlePlaceholder": "Lesson title",
    "createCourse.lessonDurationPlaceholder": "Duration",
    "createCourse.addLesson": "Add Lesson",
    "createCourse.cancel": "Cancel",
    "createCourse.creating": "Creating...",
    "createCourse.createCourse": "Create Course",
    "createCourse.successTitle": "Course Created!",
    "createCourse.successMessage": "Your course has been created successfully. You can now add content and publish it.",
  },
  ar: {
    // Navbar
    "nav.courses": "الدورات",
    "nav.blog": "المدونة",
    "nav.about": "من نحن",
    "nav.contact": "اتصل بنا",
    "nav.login": "تسجيل الدخول",
    "nav.getStarted": "ابدأ مجاناً",
    
    // Hero
    "hero.badge": "🎓 موثوق به من قبل 2 مليون+ متعلم حول العالم",
    "hero.title1": "اتقن مهارات جديدة",
    "hero.title2": "غيّر مستقبلك",
    "hero.subtitle": "انضم إلى آلاف المتعلمين الذين يطورون حياتهم المهنية من خلال دورات يقودها خبراء في التكنولوجيا والأعمال والمهارات الإبداعية.",
    "hero.cta1": "ابدأ التعلم مجاناً",
    "hero.cta2": "شاهد العرض",
    "hero.stats.students": "طالب نشط",
    "hero.stats.courses": "دورة",
    "hero.stats.rating": "تقييم",
    
    // Stats Section
    "stats.students": "طالب نشط",
    "stats.courses": "دورة متخصصة",
    "stats.countries": "دولة",
    "stats.success": "نسبة النجاح",
    
    // Features
    "features.badge": "لماذا تختارنا",
    "features.title1": "كل ما تحتاجه",
    "features.title2": " للنجاح",
    "features.subtitle": "منصتنا مصممة لنجاحك، تقدم أدوات وموارد شاملة للتعلم الفعال.",
    "features.expertCourses": "دورات يقودها خبراء",
    "features.expertCoursesDesc": "تعلم من محترفين في الصناعة وقادة الفكر الذين يجلبون خبرة حقيقية لكل درس.",
    "features.interactive": "تعلم تفاعلي",
    "features.interactiveDesc": "شارك في مشاريع عملية واختبارات وتمارين برمجية تعزز معرفتك.",
    "features.pace": "تعلم بسرعتك",
    "features.paceDesc": "الوصول إلى الدورات في أي وقت وأي مكان. منصتنا المرنة تتكيف مع جدولك وأسلوب تعلمك.",
    "features.certificates": "احصل على شهادات",
    "features.certificatesDesc": "اعرض إنجازاتك بشهادات معترف بها في الصناعة عند إتمام الدورة.",
    "features.community": "دعم المجتمع",
    "features.communityDesc": "انضم إلى مجتمع عالمي من المتعلمين. تعاون وناقش وتطور معاً.",
    "features.lifetime": "وصول مدى الحياة",
    "features.lifetimeDesc": "اشترِ مرة واحدة، تعلم للأبد. احصل على وصول مدى الحياة لجميع مواد الدورة والتحديثات المستقبلية.",
    
    // Courses
    "courses.badge": "الدورات الشائعة",
    "courses.title1": "اكتشف",
    "courses.title2": " أفضل دوراتنا",
    "courses.subtitle": "اكتشف دورات مختارة بعناية مصممة لمساعدتك على تحقيق أهدافك التعليمية وتطوير حياتك المهنية.",
    "courses.viewAll": "عرض جميع الدورات",
    "courses.enroll": "سجل الآن",
    "courses.students": "طالب",
    
    // CTA
    "cta.title1": "مستعد لبدء",
    "cta.title2": "رحلة التعلم؟",
    "cta.subtitle": "انضم إلى أكثر من 2 مليون متعلم حول العالم واتخذ الخطوة الأولى نحو تحقيق أهدافك. ابدأ التعلم مجاناً اليوم.",
    "cta.button1": "ابدأ مجاناً",
    "cta.button2": "تصفح الدورات",
    "cta.note": "لا حاجة لبطاقة ائتمان • خطة مجانية للأبد متاحة",
    
    // Footer
    "footer.description": "تمكين المتعلمين حول العالم بتعليم عالي الجودة ودورات يقودها خبراء.",
    "footer.platform": "المنصة",
    "footer.company": "الشركة",
    "footer.support": "الدعم",
    "footer.allCourses": "جميع الدورات",
    "footer.enterprise": "للمؤسسات",
    "footer.becomeInstructor": "كن مدرباً",
    "footer.mobileApp": "تطبيق الجوال",
    "footer.aboutUs": "من نحن",
    "footer.careers": "الوظائف",
    "footer.press": "الصحافة",
    "footer.helpCenter": "مركز المساعدة",
    "footer.contactUs": "اتصل بنا",
    "footer.privacy": "سياسة الخصوصية",
    "footer.terms": "شروط الخدمة",
    "footer.cookies": "ملفات تعريف الارتباط",
    "footer.rights": "جميع الحقوق محفوظة.",
    
    // About Page
    "about.heroTitle1": "نغير الحياة من خلال",
    "about.heroTitle2": "التعليم",
    "about.heroSubtitle": "نحن في مهمة لجعل التعليم العالمي متاحاً للجميع، في كل مكان. انضم إلينا في تشكيل مستقبل التعلم.",
    "about.ourMission": "مهمتنا",
    "about.missionText": "تمكين الأفراد حول العالم بالمهارات والمعرفة التي يحتاجونها للنجاح في العصر الرقمي. نؤمن أن التعليم الجيد يجب أن يكون حقاً متاحاً للجميع وليس امتيازاً.",
    "about.ourVision": "رؤيتنا",
    "about.visionText": "أن نصبح أكثر منصة تعليمية موثوقة وابتكارية في العالم، حيث يمكن لأي شخص اكتساب مهارات جديدة وتطوير حياته المهنية وإطلاق إمكاناته الكاملة من خلال التعليم التحويلي.",
    "about.coreValues": "قيمنا الأساسية",
    "about.valuesSubtitle": "هذه المبادئ توجه كل ما نفعله وتشكل ثقافتنا",
    "about.excellence": "التميز",
    "about.excellenceDesc": "نسعى للجودة العالية في كل ما نصنعه، من محتوى الدورات إلى تجربة المستخدم.",
    "about.passion": "الشغف",
    "about.passionDesc": "نحن مدفوعون بحب حقيقي للتعليم ومساعدة الآخرين على تحقيق إمكاناتهم.",
    "about.community": "المجتمع",
    "about.communityDesc": "نؤمن أن التعلم أفضل معاً ونعزز مجتمعاً عالمياً داعماً.",
    "about.accessibility": "الوصولية",
    "about.accessibilityDesc": "يجب أن يكون التعليم متاحاً للجميع، بغض النظر عن الموقع أو الخلفية.",
    "about.meetTeam": "تعرف على فريقنا",
    "about.teamSubtitle": "معلمون وتقنيون متحمسون يعملون معاً لإحداث ثورة في التعلم",
    "about.ourJourney": "رحلتنا",
    "about.journeySubtitle": "من فكرة صغيرة إلى منصة عالمية",
    "about.studentsWorldwide": "طالب حول العالم",
    "about.expertInstructors": "مدرب خبير",
    "about.coursesAvailable": "دورة متاحة",
    "about.countriesReached": "دولة تم الوصول إليها",
    "about.joinTeam": "انضم إلى فريقنا المتنامي",
    "about.joinTeamDesc": "نبحث دائماً عن أفراد متحمسين لمساعدتنا في تحويل التعليم. تحقق من الوظائف المتاحة وكن جزءاً من شيء ذي معنى.",
    "about.viewPositions": "عرض الوظائف المتاحة",
    
    // Contact Page
    "contact.badge": "اتصل بنا",
    "contact.heroTitle1": "نحب أن",
    "contact.heroTitle2": "نسمع منك",
    "contact.heroSubtitle": "هل لديك أسئلة حول دوراتنا أو تحتاج مساعدة في رحلة تعلمك؟ فريقنا هنا لمساعدتك في كل خطوة.",
    "contact.sendMessage": "أرسل لنا رسالة",
    "contact.fullName": "الاسم الكامل",
    "contact.emailAddress": "البريد الإلكتروني",
    "contact.subject": "الموضوع",
    "contact.subjectPlaceholder": "كيف يمكننا مساعدتك؟",
    "contact.message": "الرسالة",
    "contact.messagePlaceholder": "أخبرنا المزيد عن استفسارك...",
    "contact.send": "إرسال الرسالة",
    "contact.sending": "جاري الإرسال...",
    "contact.quickContact": "التواصل السريع",
    "contact.emailUs": "راسلنا",
    "contact.weRespond": "نرد خلال 24 ساعة",
    "contact.callUs": "اتصل بنا",
    "contact.callHours": "الإثنين-الجمعة، 9 صباحاً - 6 مساءً",
    "contact.supportOptions": "خيارات الدعم",
    "contact.liveChat": "الدردشة المباشرة",
    "contact.liveChatDesc": "احصل على مساعدة فورية من فريق الدعم",
    "contact.startChat": "ابدأ الدردشة",
    "contact.available247": "متاح 24/7",
    "contact.helpCenter": "مركز المساعدة",
    "contact.helpCenterDesc": "تصفح قاعدة المعرفة الشاملة",
    "contact.visitHelpCenter": "زيارة مركز المساعدة",
    "contact.selfService": "خدمة ذاتية",
    "contact.documentation": "التوثيق",
    "contact.documentationDesc": "أدلة تفصيلية ومراجع API",
    "contact.viewDocs": "عرض التوثيق",
    "contact.alwaysAvailable": "متاح دائماً",
    "contact.ourOffices": "مكاتبنا",
    "contact.officesSubtitle": "قم بزيارتنا في أحد مواقعنا العالمية أو تواصل مع أقرب مكتب.",
    "contact.messageSent": "تم إرسال الرسالة!",
    "contact.messageSuccess": "سنرد عليك خلال 24 ساعة.",
    
    // Courses Page
    "coursesPage.title": "اكتشف",
    "coursesPage.titleHighlight": "دوراتنا",
    "coursesPage.subtitle": "اكتشف مئات الدورات التي يدرسها مدربون خبراء",
    "coursesPage.searchPlaceholder": "ابحث عن دورات أو مدربين...",
    "coursesPage.all": "الكل",
    "coursesPage.development": "التطوير",
    "coursesPage.dataScience": "علم البيانات",
    "coursesPage.design": "التصميم",
    "coursesPage.marketing": "التسويق",
    "coursesPage.itSecurity": "تكنولوجيا المعلومات والأمن",
    "coursesPage.allLevels": "جميع المستويات",
    "coursesPage.beginner": "مبتدئ",
    "coursesPage.intermediate": "متوسط",
    "coursesPage.advanced": "متقدم",
    "coursesPage.allPrices": "جميع الأسعار",
    "coursesPage.under50": "أقل من 50$",
    "coursesPage.showing": "عرض",
    "coursesPage.coursesCount": "دورة",
    "coursesPage.noCoursesFound": "لم يتم العثور على دورات",
    "coursesPage.clearFilters": "مسح الفلاتر",
    "coursesPage.by": "بواسطة",
    "coursesPage.enroll": "سجل",
    "coursesPage.bestseller": "الأكثر مبيعاً",
    "coursesPage.hot": "رائج",
    "coursesPage.new": "جديد",
    "coursesPage.popular": "شائع",
    "coursesPage.hours": "ساعة",
    
    // Pricing Section
    "pricing.badge": "خطط الأسعار",
    "pricing.title1": "أسعار بسيطة",
    "pricing.title2": " وشفافة",
    "pricing.subtitle": "اختر الخطة التي تناسب أهدافك التعليمية. يمكنك الترقية أو التخفيض في أي وقت.",
    "pricing.free": "مجاني",
    "pricing.freeDesc": "مثالي للبدء",
    "pricing.pro": "برو",
    "pricing.proDesc": "الأفضل للمتعلمين الجادين",
    "pricing.team": "فريق",
    "pricing.teamDesc": "للفرق والمؤسسات",
    "pricing.month": "/شهر",
    "pricing.mostPopular": "الأكثر شعبية",
    "pricing.startFree": "ابدأ مجاناً",
    "pricing.startProTrial": "ابدأ تجربة برو",
    "pricing.contactSales": "تواصل مع المبيعات",
    "pricing.feature.free1": "الوصول إلى 10 دورات مجانية",
    "pricing.feature.free2": "مسارات تعلم أساسية",
    "pricing.feature.free3": "الوصول لمنتدى المجتمع",
    "pricing.feature.free4": "الوصول لتطبيق الجوال",
    "pricing.feature.pro1": "الوصول إلى 200+ دورة",
    "pricing.feature.pro2": "مسارات تعلم مخصصة",
    "pricing.feature.pro3": "شهادة إتمام",
    "pricing.feature.pro4": "دعم أولوي",
    "pricing.feature.pro5": "التحميل للعمل بدون إنترنت",
    "pricing.feature.pro6": "مراجعات المشاريع",
    "pricing.feature.team1": "كل شيء في برو",
    "pricing.feature.team2": "لوحة إدارة الفريق",
    "pricing.feature.team3": "تتبع التقدم والتحليلات",
    "pricing.feature.team4": "مسارات تعلم مخصصة",
    "pricing.feature.team5": "مدير حساب مخصص",
    "pricing.feature.team6": "الوصول لـ API",
    
    // Testimonials Section
    "testimonials.badge": "قصص النجاح",
    "testimonials.title1": "ماذا يقول",
    "testimonials.title2": " طلابنا",
    "testimonials.subtitle": "انضم إلى آلاف المتعلمين الراضين الذين غيروا حياتهم المهنية مع منصتنا.",
    "testimonials.name1": "أحمد محمد",
    "testimonials.role1": "مطور برمجيات",
    "testimonials.company1": "جوجل",
    "testimonials.content1": "غيّرت EduLearn مسيرتي المهنية بالكامل. الدورات شاملة ومنظمة بشكل جيد، والمدربون متحمسون حقاً للتعليم.",
    "testimonials.name2": "سارة أحمد",
    "testimonials.role2": "مصممة تجربة المستخدم",
    "testimonials.company2": "سبوتيفاي",
    "testimonials.content2": "انتقلت من عدم معرفة أي شيء عن التصميم إلى الحصول على وظيفة أحلامي. المشاريع العملية وملاحظات المرشدين كانت لا تقدر بثمن.",
    "testimonials.name3": "محمد علي",
    "testimonials.role3": "محلل بيانات",
    "testimonials.company3": "أمازون",
    "testimonials.content3": "منهج علم البيانات هنا ممتاز. المشاريع الواقعية والمهارات المطلوبة في الصناعة ساعدتني على التميز في المقابلات.",
    "testimonials.at": "في",
    
    // Blog Page
    "blog.badge": "مدونتنا",
    "blog.title1": "رؤى و",
    "blog.title2": "موارد",
    "blog.subtitle": "ابق على اطلاع بأحدث الاتجاهات في التعليم والتكنولوجيا والتطوير المهني من خلال مقالاتنا المكتوبة من قبل خبراء.",
    "blog.searchPlaceholder": "ابحث في المقالات...",
    "blog.all": "الكل",
    "blog.career": "المهنة",
    "blog.development": "التطوير",
    "blog.aiMl": "الذكاء الاصطناعي",
    "blog.education": "التعليم",
    "blog.cloud": "السحابة",
    "blog.featured": "المقالات المميزة",
    "blog.allArticles": "جميع المقالات",
    "blog.articles": "مقالات",
    "blog.noArticles": "لم يتم العثور على مقالات تطابق معاييرك.",
    "blog.newsletter": "اشترك في نشرتنا الإخبارية",
    "blog.newsletterDesc": "احصل على أحدث المقالات والدروس ونصائح التعلم مباشرة في بريدك الإلكتروني.",
    "blog.emailPlaceholder": "أدخل بريدك الإلكتروني",
    "blog.subscribe": "اشترك",
    "blog.minRead": "دقيقة قراءة",
    
    // Course Detail Page
    "courseDetail.backToCourses": "العودة للدورات",
    "courseDetail.bestseller": "الأكثر مبيعاً",
    "courseDetail.updated": "محدث",
    "courseDetail.ratings": "تقييم",
    "courseDetail.students": "طالب",
    "courseDetail.createdBy": "إنشاء بواسطة",
    "courseDetail.lectures": "محاضرة",
    "courseDetail.certificateIncluded": "شهادة مضمنة",
    "courseDetail.previewCourse": "معاينة هذه الدورة",
    "courseDetail.off": "خصم",
    "courseDetail.enrollNow": "سجل الآن",
    "courseDetail.addToWishlist": "أضف للمفضلة",
    "courseDetail.moneyBack": "ضمان استرداد الأموال خلال 30 يوماً",
    "courseDetail.courseIncludes": "تتضمن هذه الدورة:",
    "courseDetail.share": "مشاركة",
    "courseDetail.whatYouLearn": "ماذا ستتعلم",
    "courseDetail.requirements": "المتطلبات",
    "courseDetail.courseCurriculum": "منهج الدورة",
    "courseDetail.sections": "قسم",
    "courseDetail.preview": "معاينة",
    "courseDetail.yourInstructor": "المدرب",
    "courseDetail.instructorRating": "تقييم المدرب",
    "courseDetail.courses": "دورة",
    "courseDetail.studentReviews": "تقييمات الطلاب",
    "courseDetail.courseRating": "تقييم الدورة",
    "courseDetail.showAllReviews": "عرض جميع التقييمات",
    "courseDetail.hoursOnDemand": "ساعة من الفيديو",
    "courseDetail.lecturesCovering": "محاضرة تغطي جميع المواضيع",
    "courseDetail.realWorldProjects": "مشروع واقعي",
    "courseDetail.downloadableResources": "موارد قابلة للتحميل",
    "courseDetail.certificateCompletion": "شهادة إتمام",
    "courseDetail.lifetimeAccess": "وصول مدى الحياة",
    "courseDetail.mobileAccess": "الوصول عبر الجوال والتلفزيون",
    "courseDetail.moneyBackGuarantee": "ضمان استرداد الأموال خلال 30 يوماً",
    "courseDetail.noProgramming": "لا تحتاج خبرة برمجية",
    "courseDetail.computerInternet": "حاسوب متصل بالإنترنت",
    "courseDetail.desireToLearn": "الرغبة في التعلم وبناء المشاريع",
    "courseDetail.buildProjects": "بناء 15+ مشروع ويب واقعي",
    "courseDetail.masterHTML": "إتقان HTML5 و CSS3 و JavaScript الحديثة",
    "courseDetail.createResponsive": "إنشاء مواقع متجاوبة من الصفر",
    "courseDetail.learnReact": "تعلم React وبناء تطبيقات الصفحة الواحدة",
    "courseDetail.understandBackend": "فهم تطوير الخادم مع Node.js",
    "courseDetail.workWithDB": "العمل مع قواعد البيانات مثل MongoDB",
    "courseDetail.deployCloud": "نشر التطبيقات على السحابة",
    "courseDetail.writeClean": "كتابة كود نظيف وقابل للصيانة",
    
    // Dashboard Page
    "dashboard.student": "طالب",
    "dashboard.admin": "مدير",
    "dashboard.myCourses": "دوراتي",
    "dashboard.progress": "التقدم",
    "dashboard.certificates": "الشهادات",
    "dashboard.schedule": "الجدول",
    "dashboard.profile": "الملف الشخصي",
    "dashboard.logout": "تسجيل الخروج",
    "dashboard.welcomeBack": "مرحباً بعودتك، جون! 👋",
    "dashboard.continueJourney": "تابع رحلة تعلمك. أنت تحرز تقدماً رائعاً!",
    "dashboard.enrolledCourses": "الدورات المسجلة",
    "dashboard.hoursLearned": "ساعات التعلم",
    "dashboard.avgProgress": "متوسط التقدم",
    "dashboard.continueLearning": "تابع التعلم",
    "dashboard.viewAll": "عرض الكل",
    "dashboard.next": "التالي:",
    "dashboard.continue": "متابعة",
    "dashboard.by": "بواسطة",
    "dashboard.recentAchievements": "الإنجازات الأخيرة",
    "dashboard.upcomingDeadlines": "المواعيد القادمة",
    "dashboard.adminDashboard": "لوحة الإدارة 🎛️",
    "dashboard.manageDescription": "إدارة الدورات والطلاب وتحليلات المنصة.",
    "dashboard.totalStudents": "إجمالي الطلاب",
    "dashboard.totalCourses": "إجمالي الدورات",
    "dashboard.revenue": "الإيرادات",
    "dashboard.certificatesIssued": "الشهادات الصادرة",
    "dashboard.quickActions": "إجراءات سريعة",
    "dashboard.addNewCourse": "إضافة دورة جديدة",
    "dashboard.manageUsers": "إدارة المستخدمين",
    "dashboard.viewAnalytics": "عرض التحليلات",
    "dashboard.settings": "الإعدادات",
    "dashboard.recentActivity": "النشاط الأخير",
    "dashboard.firstCourse": "الدورة الأولى",
    "dashboard.firstCourseDesc": "سجلت في دورتك الأولى",
    "dashboard.bookworm": "عاشق الكتب",
    "dashboard.bookwormDesc": "أكملت 5 دروس في يوم واحد",
    "dashboard.risingStar": "نجم صاعد",
    "dashboard.risingStarDesc": "حصلت على شهادتك الأولى",
    
    // Teacher Dashboard
    "dashboard.teacher": "معلم",
    "dashboard.teacherDashboard": "لوحة تحكم المعلم 📚",
    "dashboard.teacherDescription": "إدارة دوراتك وطلابك وتتبع الأداء.",
    "dashboard.myCoursesTaught": "دوراتي",
    "dashboard.totalStudentsEnrolled": "إجمالي الطلاب",
    "dashboard.courseRevenue": "إيرادات الدورات",
    "dashboard.avgRating": "متوسط التقييم",
    "dashboard.manageCourses": "إدارة الدورات",
    "dashboard.createCourse": "إنشاء دورة",
    "dashboard.editCourse": "تعديل الدورة",
    "dashboard.viewEnrollments": "عرض التسجيلات",
    "dashboard.coursePerformance": "أداء الدورات",
    "dashboard.studentProgress": "تقدم الطلاب",
    "dashboard.recentEnrollments": "التسجيلات الأخيرة",
    "dashboard.courseFeedback": "ملاحظات الدورة",
    "dashboard.uploadContent": "رفع المحتوى",
    "dashboard.viewReviews": "عرض التقييمات",
    "dashboard.respondToQuestions": "الرد على الأسئلة",
    "dashboard.pendingQuestions": "أسئلة معلقة",
    "dashboard.courseStats": "إحصائيات الدورة",
    "dashboard.earnings": "الأرباح",
    "dashboard.withdrawFunds": "سحب الأموال",
    "dashboard.paymentHistory": "سجل المدفوعات",
    
    // Blog Post Page
    "blogPost.backToBlog": "العودة للمدونة",
    "blogPost.articleNotFound": "المقال غير موجود",
    "blogPost.like": "إعجاب",
    "blogPost.save": "حفظ",
    "blogPost.share": "مشاركة",
    "blogPost.shareArticle": "شارك هذا المقال",
    "blogPost.relatedArticles": "مقالات ذات صلة",
    "blogPost.minRead": "دقيقة قراءة",
    
    // Help Center Page
    "helpCenter.title": "كيف يمكننا مساعدتك؟",
    "helpCenter.subtitle": "ابحث في قاعدة المعرفة أو تصفح الفئات أدناه",
    "helpCenter.searchPlaceholder": "ابحث في مقالات المساعدة...",
    "helpCenter.popularArticles": "المقالات الشائعة",
    "helpCenter.browseByCategory": "تصفح حسب الفئة",
    "helpCenter.stillNeedHelp": "لا تزال بحاجة للمساعدة؟",
    "helpCenter.supportTeam": "فريق الدعم لدينا هنا لمساعدتك",
    "helpCenter.emailUs": "راسلنا",
    "helpCenter.emailResponse": "احصل على رد خلال 24 ساعة",
    "helpCenter.sendEmail": "إرسال بريد",
    "helpCenter.liveChat": "الدردشة المباشرة",
    "helpCenter.chatRealTime": "تحدث معنا في الوقت الفعلي",
    "helpCenter.startChat": "ابدأ الدردشة",
    "helpCenter.callUs": "اتصل بنا",
    "helpCenter.callHours": "الإثنين-الجمعة، 9 صباحاً - 6 مساءً",
    "helpCenter.gettingStarted": "البدء",
    "helpCenter.gettingStartedDesc": "تعلم أساسيات استخدام EduLearn",
    "helpCenter.coursesLearning": "الدورات والتعلم",
    "helpCenter.coursesLearningDesc": "كل شيء عن أخذ الدورات",
    "helpCenter.paymentsBilling": "المدفوعات والفوترة",
    "helpCenter.paymentsBillingDesc": "إدارة المدفوعات والاشتراكات",
    "helpCenter.accountManagement": "إدارة الحساب",
    "helpCenter.accountManagementDesc": "تحديث إعدادات حسابك",
    "helpCenter.technicalIssues": "المشاكل التقنية",
    "helpCenter.technicalIssuesDesc": "حل المشاكل الشائعة",
    "helpCenter.communitySupport": "المجتمع والدعم",
    "helpCenter.communitySupportDesc": "تواصل مع الآخرين",
    "helpCenter.article1": "كيفية إنشاء حساب",
    "helpCenter.article2": "التنقل في المنصة",
    "helpCenter.article3": "العثور على دورتك الأولى",
    "helpCenter.article4": "إعداد ملفك الشخصي",
    "helpCenter.article5": "التسجيل في الدورات",
    "helpCenter.article6": "تتبع تقدمك",
    "helpCenter.article7": "تحميل الموارد",
    "helpCenter.article8": "الحصول على الشهادات",
    "helpCenter.article9": "طرق الدفع",
    "helpCenter.article10": "خطط الاشتراك",
    "helpCenter.article11": "سياسة الاسترداد",
    "helpCenter.article12": "الفواتير والإيصالات",
    "helpCenter.article13": "تغيير كلمة المرور",
    "helpCenter.article14": "تحديث البريد الإلكتروني",
    "helpCenter.article15": "إعدادات الخصوصية",
    "helpCenter.article16": "حذف الحساب",
    "helpCenter.article17": "مشاكل تشغيل الفيديو",
    "helpCenter.article18": "مشاكل تسجيل الدخول",
    "helpCenter.article19": "توافق المتصفح",
    "helpCenter.article20": "مساعدة تطبيق الجوال",
    "helpCenter.article21": "منتديات النقاش",
    "helpCenter.article22": "مجموعات الدراسة",
    "helpCenter.article23": "التواصل مع المدربين",
    "helpCenter.article24": "الإبلاغ عن المشاكل",
    "helpCenter.popular1": "كيف أحصل على استرداد؟",
    "helpCenter.popular2": "هل يمكنني تحميل فيديوهات الدورات؟",
    "helpCenter.popular3": "كيف تعمل الشهادات؟",
    "helpCenter.popular4": "لماذا لا يعمل الفيديو؟",
    "helpCenter.popular5": "كيفية إلغاء اشتراكي",
    
    // Privacy Policy Page
    "privacy.title": "سياسة الخصوصية",
    "privacy.subtitle": "خصوصيتك مهمة بالنسبة لنا. توضح هذه السياسة كيف نجمع ونستخدم ونحمي معلوماتك الشخصية.",
    "privacy.lastUpdated": "آخر تحديث: ديسمبر 2024",
    "privacy.questions": "أسئلة حول الخصوصية؟",
    "privacy.contactText": "إذا كانت لديك أي أسئلة حول سياسة الخصوصية هذه أو ممارسات البيانات لدينا، يرجى التواصل مع مسؤول حماية البيانات على:",
    "privacy.section1Title": "المعلومات التي نجمعها",
    "privacy.section1Content": "نجمع المعلومات التي تقدمها لنا مباشرة، مثل عند إنشاء حساب أو التسجيل في دورة أو إجراء عملية شراء أو التواصل معنا للحصول على الدعم. يشمل ذلك:\n\n• المعلومات الشخصية (الاسم، البريد الإلكتروني، رقم الهاتف)\n• معلومات الدفع (تتم معالجتها بأمان من خلال مزودي الدفع لدينا)\n• بيانات تقدم الدورة وإتمامها\n• التواصل مع المدربين والطلاب الآخرين\n• الملاحظات واستجابات الاستطلاعات",
    "privacy.section2Title": "كيف نستخدم معلوماتك",
    "privacy.section2Content": "نستخدم المعلومات التي نجمعها من أجل:\n\n• توفير وصيانة وتحسين خدماتنا\n• معالجة المعاملات وإرسال المعلومات ذات الصلة\n• إرسال إشعارات تقنية وتحديثات ورسائل دعم\n• الرد على تعليقاتك وأسئلتك وطلباتك\n• تخصيص تجربة التعلم الخاصة بك\n• مراقبة وتحليل الاتجاهات والاستخدام والأنشطة",
    "privacy.section3Title": "مشاركة المعلومات",
    "privacy.section3Content": "لا نبيع أو نتاجر أو ننقل معلوماتك الشخصية إلى أطراف خارجية إلا:\n\n• بموافقتك\n• للمدربين للدورات المسجل فيها\n• لمقدمي الخدمات الذين يساعدون في عملياتنا\n• للامتثال للالتزامات القانونية\n• لحماية حقوقنا ومنع الاحتيال",
    "privacy.section4Title": "أمان البيانات",
    "privacy.section4Content": "ننفذ تدابير تقنية وتنظيمية مناسبة لحماية معلوماتك الشخصية:\n\n• تشفير البيانات أثناء النقل وفي السكون\n• تقييمات وفحوصات أمنية منتظمة\n• ضوابط الوصول والمصادقة\n• مراكز بيانات آمنة مع مراقبة على مدار الساعة\n• تدريب الموظفين على حماية البيانات",
    "privacy.section5Title": "حقوقك",
    "privacy.section5Content": "لديك الحق في:\n\n• الوصول إلى معلوماتك الشخصية\n• تصحيح البيانات غير الدقيقة\n• طلب حذف بياناتك\n• الاعتراض على معالجة بياناتك\n• تصدير بياناتك بتنسيق قابل للنقل\n• سحب الموافقة في أي وقت",
    "privacy.section6Title": "ملفات تعريف الارتباط والتتبع",
    "privacy.section6Content": "نستخدم ملفات تعريف الارتباط وتقنيات التتبع المماثلة من أجل:\n\n• تذكر تفضيلاتك وإعداداتك\n• فهم كيفية استخدامك لمنصتنا\n• تقديم محتوى وإعلانات ذات صلة\n• تحليل وتحسين خدماتنا\n\nيمكنك التحكم في ملفات تعريف الارتباط من خلال إعدادات متصفحك.",
    
    // Create Course Page
    "createCourse.backToDashboard": "العودة إلى لوحة التحكم",
    "createCourse.title": "إنشاء دورة جديدة",
    "createCourse.subtitle": "املأ التفاصيل أدناه لإنشاء دورتك. يمكنك تعديلها لاحقاً.",
    "createCourse.basicInfo": "المعلومات الأساسية",
    "createCourse.courseTitle": "عنوان الدورة",
    "createCourse.courseTitlePlaceholder": "مثال: معسكر تطوير الويب الكامل",
    "createCourse.shortDescription": "وصف مختصر",
    "createCourse.shortDescriptionPlaceholder": "نظرة عامة موجزة على دورتك (150 حرف كحد أقصى)",
    "createCourse.fullDescription": "الوصف الكامل",
    "createCourse.fullDescriptionPlaceholder": "وصف تفصيلي لما سيتعلمه الطلاب...",
    "createCourse.category": "الفئة",
    "createCourse.selectCategory": "اختر فئة",
    "createCourse.level": "المستوى",
    "createCourse.selectLevel": "اختر مستوى",
    "createCourse.pricing": "التسعير",
    "createCourse.price": "السعر (دولار)",
    "createCourse.discountPrice": "سعر الخصم (اختياري)",
    "createCourse.durationMedia": "المدة والوسائط",
    "createCourse.estimatedDuration": "المدة المقدرة",
    "createCourse.durationPlaceholder": "مثال: 20 ساعة",
    "createCourse.thumbnail": "صورة الدورة",
    "createCourse.uploadThumbnail": "انقر لرفع صورة (JPG, PNG)",
    "createCourse.curriculum": "المنهج الدراسي",
    "createCourse.addSection": "إضافة قسم",
    "createCourse.section": "القسم",
    "createCourse.sectionTitlePlaceholder": "عنوان القسم (مثال: البداية)",
    "createCourse.lessonTitlePlaceholder": "عنوان الدرس",
    "createCourse.lessonDurationPlaceholder": "المدة",
    "createCourse.addLesson": "إضافة درس",
    "createCourse.cancel": "إلغاء",
    "createCourse.creating": "جاري الإنشاء...",
    "createCourse.createCourse": "إنشاء الدورة",
    "createCourse.successTitle": "تم إنشاء الدورة!",
    "createCourse.successMessage": "تم إنشاء دورتك بنجاح. يمكنك الآن إضافة المحتوى ونشرها.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  const isRTL = language === "ar";

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.dir = isRTL ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
